from odoo import api, models, fields
from odoo.exceptions import ValidationError
from odoo.addons.metrc.constants.metrc import *
from odoo.addons.metrc.constants.functions import *
import base64

class StudentRecord(models.Model):
    _name = "student.student"
    name = fields.Char(string='Name', required=True)
    middle_name = fields.Char(string='Middle Name', required=True)
    last_name = fields.Char(string='Last Name', required=True)
    photo = fields.Binary(string='Photo')
    student_age = fields.Integer(string='Age')
    student_dob = fields.Date(string="Date of Birth")
    student_gender = fields.Selection([('m', 'Male'), ('f', 'Female'), ('o', 'Other')], string='Gender')

class MetrcPackage(models.Model):
    _name = "metrc.packages"
    label = fields.Char(string='Label')
    name = fields.Char(string='Name')
    metrc_id = fields.Integer(string='Metrc id', required=True)
    metrc_package_type = fields.Char(string='Metrc package type')
    metrc_room_id = fields.Integer(string='Age')
    metrc_packaged_date = fields.Date(string='Metrc packaged date')
    metrc_lab_testing_state = fields.Char(string='Metrc lab testing date') 
    metrc_lab_testing_state_date = fields.Date(string='Metrc packaged date')
    metrc_is_sample = fields.Integer(string='Metrc is sample')
    metrc_received_facility_license = fields.Char(string='Metrc recieved facility license')
    metrc_on_hold = fields.Integer(string='On hold')
    metrc_archieve_date = fields.Date(string='Metrc archived date')
    metrc_finished_date = fields.Date(string='Metrc finished date')
    metrc_item_id = fields.One2many('metrc.items', 'id')
    metrc_product_type_id = fields.Integer(string='Metrc product type id')
    metrc_unit_of_measure_name = fields.Char(string='Metrc unit of measure')
    user_id = fields.Integer(string='User id')

class MetrcRoom(models.Model):
    _name = "metrc.rooms"
    name = fields.Char(string='Metrc room name')
    metrc_id = fields.Integer(string='Metrc id')
    user_id = fields.Integer(string='User id')

class MetrcLocations(models.Model):
    _name = "metrc.locations"
    name = fields.Char(string='Metrc location name')
    metrc_id = fields.Integer(string='Metrc id')

class MetrcCategories(models.Model):
    _name = "metrc.categories"
    name = fields.Char(string='Metrc category name') 
    product_category_type = fields.Char(string='Category type') 
    quantity_type = fields.Char(string='Quantity type') 
    requires_strain = fields.Integer(string='Requires Strain', default = 0)
    requires_item_brand = fields.Integer(string='Requires Item Brand', default = 0)
    requires_administration_method = fields.Integer(string='Requires Administration Method', default = 0)
    requires_cbd_percent = fields.Integer(string='Requires CBD percent', default = 0)
    requires_cbd_content = fields.Integer(string='Requires CBD Content', default = 0)
    requires_thc_percent = fields.Integer(string='Requires THC Percent', default = 0)
    requires_thc_content = fields.Integer(string='Requires THC Content', default = 0)
    requires_unit_volume = fields.Integer(string='Requires unit volumne', default = 0)
    requires_unit_weight = fields.Integer(string='Requires unit weight', default = 0)
    requires_serving_size = fields.Integer(string='Requires serving size', default = 0)
    require_supply_duration_dates = fields.Integer(string='Requires supply duration dates', default = 0)
    requires_ingredients = fields.Integer(string='Requires ingredients', default = 0)
    requires_product_photo = fields.Integer(string='Requires product photo', default = 0)
    can_contain_seeds = fields.Integer(string='Can contain seeds', default = 0)
    can_be_remediated = fields.Integer(string='Can be remediated', default = 0)
    user_id = fields.Integer(string='User id', default = 0)
    display_name = fields.Char(string='Quantity type')

class MetrcStrains(models.Model):
    _name = "metrc.strains"
    name = fields.Char(string='Name') 
    thc_level = fields.Char(string='Metrc lab testing date') 
    cbd_level = fields.Char(string='Metrc lab testing date') 
    indica = fields.Char(string='Metrc lab testing date') 
    sativa = fields.Char(string='Metrc lab testing date') 
    genetics = fields.Char(string='Metrc lab testing date') 
    metrc_id = fields.Integer(string='Metrc id')
    test_status = fields.Char(string='Test Status')

class MetrcItems(models.Model):
    _name = "metrc.items"
    name = fields.Char(string='Metrc item name') 
    product_category_name = fields.Char(string='Metrc product category') 
    product_category_type = fields.Char(string='Metrc product category type') 
    quantity_type = fields.Char(string='Quantity type') 
    default_lab_testing_state = fields.Char(string='Default lab testing state') 
    unit_of_measure_name = fields.Char(string='Unit measure name') 
    approval_state = fields.Char(string='Approval state') 
    strain_id = fields.Integer(string='Strain id')
    strain_name = fields.Char(string='Strain name') 
    administration_method = fields.Char(string='Adminitration method') 
    cbd_percent = fields.Char(string='CBD percent') 
    cbd_content = fields.Char(string='CBD content') 
    cbd_unit_measure = fields.Char(string='CBD unit measure')
    thc_percent = fields.Char(string='THC percent')
    thc_content = fields.Char(string='THC content')
    thc_unit_measure = fields.Char(string='THC unit measure')
    unit_volume = fields.Char(string='THC unit volume')
    volume_unit_measure = fields.Char(string='Volume unit measure')
    unit_weight = fields.Char(string='Unit weight')
    weight_unit_measure = fields.Char(string='Weight unit measure')
    serving_size = fields.Char(string='Serving size')
    supply_duration_days = fields.Char(string='Supply duration days')
    unit_quantity = fields.Char(string='Unit quantity')
    quantity_unit_measure = fields.Char(string='Quantity unit measure')
    ingredients = fields.Char(string='Ingredients')
    user_id = fields.Integer(string='User id')
    metrc_id = fields.Integer(string='Metrc id')
    metrc_category_id = fields.Integer(string='Metrc category id')

class MetrcUnits(models.Model):
    _name = "metrc.units"
    name = fields.Char(string='Metrc units name')
    abbreviation = fields.Char(string='Metrc abbreviation')
    quantity_type = fields.Char(string='Metrc quantity type')

class MetrcTransfers(models.Model):
    _name = "metrc.transfers"
    metrc_id = fields.Integer(string='Metrc id')
    manifest_number = fields.Char(string='Manifest number')
    shipment_license_type = fields.Char(string='Shipment license type')
    shipper_facility_license_number = fields.Char(string='Facility license number')
    shipper_facility_name = fields.Char(string='Shipper facility name')
    name = fields.Char(string='Name')
    transporter_facility_license_number = fields.Char(string='Transporter facility license number')
    transporter_facility_name = fields.Char(string='Transporter facility name')
    driver_name = fields.Char(string='Driver name')
    driver_occupational_license_number = fields.Char(string='Driver occupational license number')
    driver_vehicle_license_number = fields.Char(string='Driver vehicle license number')
    vehicle_make = fields.Char(string='Vehicle make')
    vehicle_model = fields.Char(string='Vehicle model')
    vehicle_license_plate_number = fields.Char(string='Vehicle license plate number')
    delivery_count = fields.Integer(string='Delivery count')
    received_delivery_count = fields.Integer(string='Received delivery count')
    package_count = fields.Integer(string='Package count')
    received_package_count = fields.Integer(string='Received package count')
    contains_plant_package = fields.Integer(string='Contains plant package')
    contains_product_package = fields.Integer(string='Contains product package')
    contains_testing_sample = fields.Integer(string='Contains testing sample')
    contains_product_requires_remediation = fields.Integer(string='Contains product requires remediation')
    contains_remediated_product_package = fields.Integer(string='Contains remediated product package')
    created_date_time = fields.Date(string='Created date time')
    created_by_user_name = fields.Char(string='Created by user name')
    last_modified = fields.Date(string='Last modified ')
    delivery_id = fields.Integer(string='Delivery id')
    recipient_facility_license_number = fields.Char(string='Recipient facility license number')
    recipient_facility_name = fields.Char(string='Recipient facility name')
    shipment_type_name = fields.Char(string='Shipment type name')
    shipment_transaction_type = fields.Char(string='Shipment transaction type')
    estimated_departure_date_time = fields.Date(string='Estimated departure date time')
    actual_departure_date_time = fields.Date(string='Actual departure date time')
    estimated_arrival_date_time = fields.Date(string='Estimated arrival date time = ')
    actual_arrival_date_time = fields.Date(string='Actual arrival date time')
    delivery_package_count = fields.Integer(string='Delivery package count')
    delivery_received_package_count = fields.Integer(string='Delivery received package count')
    received_date_time = fields.Date(string='Received date time')
    user_id = fields.Integer(string='User id')

class MetrcPlantBatches(models.Model):
    _name = "metrc.plant_batches"
    metrc_id = fields.Integer(string='Metrc id', default=False)
    name = fields.Char(string='Plant batch name')
    type = fields.Char(string='Plant batch type')
    location_id = fields.Many2one('metrc.locations', string='Location', default=False)
    location_name = fields.Char(string='Location name')
    location_type_name = fields.Char(string='Location type name')
    room_id = fields.Many2one('metrc.rooms', string='Room', default=False)
    room_name = fields.Char(string='Room name')
    strain_id = fields.Many2one('metrc.strains', string='Strain id', default=False)
    strain_name = fields.Char(string='Strain name')
    untracked_count = fields.Integer(string='Untracked count')
    tracked_count = fields.Integer(string='Tracked count')
    live_count = fields.Integer(string='Live count')
    count = fields.Integer(string='Count')
    package_count = fields.Integer(string='Package count')
    harvested_count = fields.Integer(string='Harvested count')
    destroyed_count = fields.Integer(string='Destroyed count')
    source_package_id = fields.Integer(string= 'Source package id')
    source_package_label = fields.Integer(string= 'Source package label')
    source_plant_id = fields.Integer(string= 'Source plant id')
    source_plant_label = fields.Integer(string= 'Source plant label')
    planted_date = fields.Datetime(string = 'Planted date')
    last_modified = fields.Datetime(string = 'Last modified date')

class MetrcPlants(models.Model):
    _name = "metrc.plants"
    label = fields.Char(string='Label of the plant')
    state = fields.Char(string='State of the plant')
    growth_phase = fields.Char(string='Growth phase of the plant')
    plant_batch_id = fields.Many2one('metrc.plant_batches', string='Batch id of the plant', ondelete="cascade", default=False)
    plant_batch_name = fields.Char(string='Plant batch name', default = None)
    plant_batch_type_name = fields.Char(string='Plant batch type name', default = None)
    strain_id = fields.Integer(string='Strain id', default = None)
    strain_name = fields.Char(string='Strain name', default = None)
    location_id = fields.Integer(string='Location id', default = None)
    location_name = fields.Char(sting='Plants Location', default = None)
    location_type_name = fields.Char(string='Location type name', default = None)
    room_id = fields.Many2one('metrc.rooms', string='Room', default=False)
    room_name = fields.Char(string='Room name', default = None)
    patient_license_number = fields.Char(string='Patient license number', default = None)
    harvest_id = fields.Integer(string='Harvest id', default = None)
    harvested_unit_of_weight_name = fields.Char(string='Patient license number', default = None)
    harvested_unit_of_weight_abbreviation = fields.Char(string='Unit of weight abbreviation', default = None)
    harvested_wet_weight = fields.Float(string='Harvested net weight', default = None)
    harvest_count = fields.Integer(string='Harvest Count', default = None)
    is_on_hold = fields.Boolean(string='Plant on hold', default = None)
    planted_date = fields.Date(string='Planted date', default = None)
    vegetative_date = fields.Date(string='Vegetative date', default = None)
    flowering_date = fields.Date(string='Flowering date', default = None)
    harvested_date = fields.Date(string='Harvested date', default = None)
    destroyed_date = fields.Date(string='Destroyed date', default = None)
    destroyed_note = fields.Char(string='Destroyed note', default = None)
    destroyed_by_user_name = fields.Char(string='Destroyed by User Name', default = None)
    last_modified = fields.Datetime(string='Last modified date', default = None)